<a href="https://colab.research.google.com/github/elsiejy/Capstone/blob/main/Capstone_Hotel_Bookings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Overview

As a Data Analyst working for Oasis Hospitality Group, my objective is to analyse historical hotel booking data from 2015 to 2017 to understand booking demand patterns, customer characteristics and factors associated with booking cancellations.

The analysis will focus on identifying seasonal fluctuations in booking demand, understanding the hotel's key customer segments, and examining booking characteristics associated with cancellations. By uncovering these patterns and trends, the project aims to provide actionable insights to support better demand planning, optimise booking management strategies and reduce booking cancellations.

The findings will help make more informed, data-driven decisions about its booking strategies, customer targeting, and demand management.

# Part 1: Descriptive Analysis

### 1. Import libraries
Import the libaries into the notebook

In [10]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# importing sklearn module for predictive analysis
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.preprocessing import MinMaxScaler

# ignore the warnings that may appear
import warnings
warnings.filterwarnings("ignore")

### 2. Import data

Import csv files into the notebook. Here the file is hosted in github thus we will read the file directly from github

In [19]:
# load dataset1: booking.csv
booking = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Bookings.csv')
display(booking.info())
display(booking.head())
display(booking.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  int64
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119386 non-null  float64
 15  babies                          119390 non-null  int64
 16  country                         118902 non-null  object
 17  is_repeated_guest               119390 non-null  int64
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           103050 non-null  float64
 22  company                         6797 non-null    float64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(21), object(3)
memory usage: 25.5+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,1,1,1,1,1,0,342,2015,July,27,...,0,0,3,NaN,NaN,0,0.0,0,0,2015-07-01
1,2,1,1,1,1,0,737,2015,July,27,...,0,0,4,NaN,NaN,0,0.0,0,0,2015-07-01
2,3,1,1,1,1,0,7,2015,July,27,...,0,0,0,NaN,NaN,0,75.0,0,0,2015-07-02
3,4,1,2,1,1,0,13,2015,July,27,...,0,0,0,304.0,NaN,0,75.0,0,0,2015-07-02
4,5,1,3,1,1,0,14,2015,July,27,...,0,0,0,240.0,NaN,0,98.0,0,1,2015-07-03

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,...,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,0.370416,104.011416,2016.156554,27.165173,15.798241,...,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,34465.068657,0.472181,3.071532,5.250009,0.505913,0.482918,106.863097,0.707476,13.605138,8.780829,...,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2015.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,0.000000,18.000000,2016.000000,16.000000,8.000000,...,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,0.000000,69.000000,2016.000000,28.000000,16.000000,...,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,1.000000,160.000000,2017.000000,38.000000,23.000000,...,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,119390.000000,2.000000,26.000000,36.000000,3.000000,1.000000,737.000000,2017.000000,53.000000,31.000000,...,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [34]:
# print the number of null values in each column in booking
booking.isnull().sum()

Booking_ID                             0
Hotel_ID                               0
Market_Segment_ID                      0
Customer_Type_ID                       0
Reservation_ID                         0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
country                              488
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
booking_changes                        0
agent                              16340
company                           112593
days_in_waiting_list                   0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status_date                0
checkin_date                           0
dtype: int64

In [20]:
# load dataset2: customertype.csv
custtype = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/CustomerTypes.csv')
display(custtype.info())
display(custtype.head())
display(custtype.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_Type_ID  36 non-null     int64
 1   customer_type     36 non-null     object
 2   deposit_type      36 non-null     object
 3   meal              36 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.3+ KB

None

   Customer_Type_ID customer_type deposit_type meal
0                 1     Transient   No Deposit   BB
1                 2     Transient   No Deposit   FB
2                 3     Transient   No Deposit   HB
3                 4      Contract   No Deposit   BB
4                 5      Contract   No Deposit   HB

       Customer_Type_ID
count         36.000000
mean          18.500000
std           10.535654
min            1.000000
25%            9.750000
50%           18.500000
75%           27.250000
max           36.000000

In [35]:
# print the number of null values in each column in custtype
custtype.isnull().sum()

Customer_Type_ID    0
customer_type       0
deposit_type        0
meal                0
dtype: int64

In [21]:
# load dataset3: hotel.csv
hotel = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Hotels.csv')
display(hotel.info())
display(hotel.head())
display(hotel.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Hotel_ID  2 non-null      int64
 1   hotel     2 non-null      object
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

None

   Hotel_ID         hotel
0         1  Resort Hotel
1         2    City Hotel

       Hotel_ID
count  2.000000
mean   1.500000
std    0.707107
min    1.000000
25%    1.250000
50%    1.500000
75%    1.750000
max    2.000000

In [22]:
# load dataset4: marketsegment.csv
marketseg = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/MarketSegments.csv')
display(marketseg.info())
display(marketseg.head())
display(marketseg.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Market_Segment_ID     26 non-null     int64
 1   market_segment        26 non-null     object
 2   distribution_channel  26 non-null     object
dtypes: int64(1), object(2)
memory usage: 756.0+ bytes

None

   Market_Segment_ID market_segment distribution_channel
0                  1         Direct               Direct
1                  2      Corporate            Corporate
2                  3      Online TA                TA/TO
3                  4  Offline TA/TO                TA/TO
4                  5  Complementary               Direct

       Market_Segment_ID
count          26.000000
mean           13.500000
std             7.648529
min             1.000000
25%             7.250000
50%            13.500000
75%            19.750000
max            26.000000

In [23]:
# load dataset5: reservationstatus.csv
rstatus = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/ReservationStatus.csv')
display(rstatus.info())
display(rstatus.head())
display(rstatus.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reservation_ID      3 non-null      int64
 1   reservation_status  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

None

   Reservation_ID reservation_status
0               1          Check-Out
1               2           Canceled
2               3            No-Show

       Reservation_ID
count             3.0
mean              2.0
std               1.0
min               1.0
25%               1.5
50%               2.0
75%               2.5
max               3.0

Observation from booking dataset
- There are a total of 119,390 booking records
- Hotel_ID, Market_Segment_ID, Customer_Type_ID, Reservation_ID are foreign keys
- NULL values exist in children, country, agent, company
- reservation_status_date should be date time
- children, agent, and company should be int
- is_repeated_guest and is_canceled should be boolean

### 3. Data Cleansing & Preparation

Let's clean the dataset. We'll identify missing values, handle empty rows, correct data types, and prepare the dataset for analysis.

Dataset 1: Booking
1. Derive check-in date
2. Update data type for reservation_status_date
3. Update data type for is_repeated_guest and is_canceled
4. Update data type for children, agent and company
5. Handle NULL values for children, country, agent, company

In [59]:
# 1. Derive check-in date
# combine arrival_date_year, arrival_date_month and arrival_date_day_of_month into strings
booking_date_strings = (
    booking['arrival_date_year'].astype(str) + '-' +
    booking['arrival_date_month'].astype(str) + '-' +
    booking['arrival_date_day_of_month'].astype(str)
)

# convert booking_date_strings to datetime then format as YYYY-MM-DD text
booking['checkin_date'] = pd.to_datetime(booking_date_strings).dt.strftime('%Y-%m-%d')

# convert that string into a proper pandas datetime object
booking['checkin_date'] = pd.to_datetime(booking_date_strings)

# verify that first 5 rows of checkin_date
print(booking['checkin_date'].head())

0   2015-07-01
1   2015-07-01
2   2015-07-01
3   2015-07-01
4   2015-07-01
Name: checkin_date, dtype: datetime64[ns]

In [60]:
# 2. Update data type for reservation_status_date
# convert reservation_status_date to datetime format
booking['reservation_status_date'] = pd.to_datetime(booking['reservation_status_date'])

# view the first 5 rows of reservation_status_date
print(booking['reservation_status_date'].head())

0   2015-07-01
1   2015-07-01
2   2015-07-02
3   2015-07-02
4   2015-07-03
Name: reservation_status_date, dtype: datetime64[ns]

In [61]:
# 3. Update data type for is_repeated_guest and is_canceled
# change datatype from int to boolean
booking[['is_repeated_guest', 'is_canceled']] = booking[['is_repeated_guest', 'is_canceled']].astype(bool)

# verify count of is_repeated_guest and is_canceled
print(booking['is_canceled'].value_counts())
print(booking['is_repeated_guest'].value_counts())

# confirm values are only false, true
print(booking['is_canceled'].unique())
print(booking['is_repeated_guest'].unique())

is_canceled
False    75166
True     44224
Name: count, dtype: int64
is_repeated_guest
False    115580
True       3810
Name: count, dtype: int64
[False  True]
[False  True]

In [62]:
# 4. Update data type for children, agent and company
# change datatype from float to int
booking[['children', 'agent', 'company']] = booking[['children', 'agent', 'company']].astype('Int64')

In [68]:
# 5. Handle NULL values for children, country, agent, company
# handle NULL value for children by replacing NULL with 0
booking['children'] = booking['children'].fillna(0)

# handle NULL value for country by replacing NULL with UNKNOWN
booking['country'] = booking['country'].fillna('Unknown')

In [69]:
# verify null values for each column in booking
booking.isnull().sum()

Booking_ID                             0
Hotel_ID                               0
Market_Segment_ID                      0
Customer_Type_ID                       0
Reservation_ID                         0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               0
babies                                 0
country                                0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
booking_changes                        0
agent                              16340
company                           112593
days_in_waiting_list                   0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status_date                0
checkin_date                           0
dtype: int64

In [66]:
# check booking data
display(booking.info())
display(booking.head())
display(booking.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 29 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  bool
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119390 non-null  Int64
 15  babies                          119390 non-null  int64
 16  country                         118902 non-null  object
 17  is_repeated_guest               119390 non-null  bool
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           103050 non-null  Int64
 22  company                         6797 non-null    Int64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  datetime64[ns]
 28  checkin_date                    119390 non-null  datetime64[ns]
dtypes: Int64(3), bool(2), datetime64[ns](2), float64(1), int64(19), object(2)
memory usage: 25.2+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,checkin_date
0,1,1,1,1,1,False,342,2015,July,27,...,0,3,<NA>,<NA>,0,0.0,0,0,2015-07-01,2015-07-01
1,2,1,1,1,1,False,737,2015,July,27,...,0,4,<NA>,<NA>,0,0.0,0,0,2015-07-01,2015-07-01
2,3,1,1,1,1,False,7,2015,July,27,...,0,0,<NA>,<NA>,0,75.0,0,0,2015-07-02,2015-07-01
3,4,1,2,1,1,False,13,2015,July,27,...,0,0,304,<NA>,0,75.0,0,0,2015-07-02,2015-07-01
4,5,1,3,1,1,False,14,2015,July,27,...,0,0,240,<NA>,0,98.0,0,1,2015-07-03,2015-07-01

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,checkin_date
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390,119390.000000,...,119390.000000,119390.000000,103050.0,6797.0,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390
unique,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,12,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,August,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,75166,NaN,NaN,13877,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,NaN,104.011416,2016.156554,NaN,27.165173,...,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363,2016-07-30 00:24:47.883407104,2016-08-28 16:39:45.727447808
min,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.000000,2015.000000,NaN,1.000000,...,0.000000,0.000000,1.0,6.0,0.000000,-6.380000,0.000000,0.000000,2014-10-17 00:00:00,2015-07-01 00:00:00
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,NaN,18.000000,2016.000000,NaN,16.000000,...,0.000000,0.000000,9.0,62.0,0.000000,69.290000,0.000000,0.000000,2016-02-01 00:00:00,2016-03-13 00:00:00
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,NaN,69.000000,2016.000000,NaN,28.000000,...,0.000000,0.000000,14.0,179.0,0.000000,94.575000,0.000000,0.000000,2016-08-07 00:00:00,2016-09-06 00:00:00
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,NaN,160.000000,2017.000000,NaN,38.000000,...,0.000000,0.000000,229.0,270.0,0.000000,126.000000,0.000000,1.000000,2017-02-08 00:00:00,2017-03-18 00:00:00
max,119390.000000,2.000000,26.000000,36.000000,3.000000,NaN,737.000000,2017.000000,NaN,53.000000,...,72.000000,21.000000,535.0,543.0,391.000000,5400.000000,8.000000,5.000000,2017-09-14 00:00:00,2017-08-31 00:00:00
std,34465.068657,0.472181,3.071532,5.250009,0.505913,NaN,106.863097,0.707476,NaN,13.605138,...,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798,NaN,NaN