<a href="https://colab.research.google.com/github/elsiejy/Capstone/blob/main/Capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1: Descriptive Analysis

## 1. Import libraries
Import the libaries into the notebook

In [2]:
# import libraries
import pandas as pd
import numpy as np

# ignore the warnings that may appear
import warnings
warnings.filterwarnings("ignore")

## 2. Import data

Import csv files into the notebook. Here the file is hosted in github thus we will read the file directly from github

In [3]:
# load dataset1: booking.csv
bookings = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Bookings.csv')
display(bookings.info())
display(bookings.head())
display(bookings.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  int64
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119386 non-null  float64
 15  babies                          119390 non-null  int64
 16  country                         118902 non-null  object
 17  is_repeated_guest               119390 non-null  int64
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           103050 non-null  float64
 22  company                         6797 non-null    float64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(21), object(3)
memory usage: 25.5+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,1,1,1,1,1,0,342,2015,July,27,...,0,0,3,NaN,NaN,0,0.0,0,0,2015-07-01
1,2,1,1,1,1,0,737,2015,July,27,...,0,0,4,NaN,NaN,0,0.0,0,0,2015-07-01
2,3,1,1,1,1,0,7,2015,July,27,...,0,0,0,NaN,NaN,0,75.0,0,0,2015-07-02
3,4,1,2,1,1,0,13,2015,July,27,...,0,0,0,304.0,NaN,0,75.0,0,0,2015-07-02
4,5,1,3,1,1,0,14,2015,July,27,...,0,0,0,240.0,NaN,0,98.0,0,1,2015-07-03

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,...,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,0.370416,104.011416,2016.156554,27.165173,15.798241,...,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,34465.068657,0.472181,3.071532,5.250009,0.505913,0.482918,106.863097,0.707476,13.605138,8.780829,...,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2015.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,0.000000,18.000000,2016.000000,16.000000,8.000000,...,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,0.000000,69.000000,2016.000000,28.000000,16.000000,...,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,1.000000,160.000000,2017.000000,38.000000,23.000000,...,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,119390.000000,2.000000,26.000000,36.000000,3.000000,1.000000,737.000000,2017.000000,53.000000,31.000000,...,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [4]:
# print the number of null values in each column in booking
bookings.isnull().sum()

Booking_ID                             0
Hotel_ID                               0
Market_Segment_ID                      0
Customer_Type_ID                       0
Reservation_ID                         0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
country                              488
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
booking_changes                        0
agent                              16340
company                           112593
days_in_waiting_list                   0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status_date                0
dtype: int64

In [5]:
# load dataset2: customertype.csv
cust_type = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Customer_Types.csv')
display(cust_type.info())
display(cust_type.head())
display(cust_type.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_Type_ID  36 non-null     int64
 1   customer_type     36 non-null     object
 2   deposit_type      36 non-null     object
 3   meal              36 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.3+ KB

None

   Customer_Type_ID customer_type deposit_type meal
0                 1     Transient   No Deposit   BB
1                 2     Transient   No Deposit   FB
2                 3     Transient   No Deposit   HB
3                 4      Contract   No Deposit   BB
4                 5      Contract   No Deposit   HB

       Customer_Type_ID
count         36.000000
mean          18.500000
std           10.535654
min            1.000000
25%            9.750000
50%           18.500000
75%           27.250000
max           36.000000

In [6]:
# print the number of null values in each column in cust_type
cust_type.isnull().sum()

Customer_Type_ID    0
customer_type       0
deposit_type        0
meal                0
dtype: int64

In [7]:
# load dataset3: hotel.csv
hotel_type = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Hotels.csv')
display(hotel_type.info())
display(hotel_type.head())
display(hotel_type.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Hotel_ID  2 non-null      int64
 1   hotel     2 non-null      object
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

None

   Hotel_ID         hotel
0         1  Resort Hotel
1         2    City Hotel

       Hotel_ID
count  2.000000
mean   1.500000
std    0.707107
min    1.000000
25%    1.250000
50%    1.500000
75%    1.750000
max    2.000000

In [8]:
# print the number of null values in each column in hotel_type
hotel_type.isnull().sum()

Hotel_ID    0
hotel       0
dtype: int64

In [9]:
# load dataset4: marketsegment.csv
market_seg = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Market_Segments.csv')
display(market_seg.info())
display(market_seg.head())
display(market_seg.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Market_Segment_ID     26 non-null     int64
 1   market_segment        26 non-null     object
 2   distribution_channel  26 non-null     object
dtypes: int64(1), object(2)
memory usage: 756.0+ bytes

None

   Market_Segment_ID market_segment distribution_channel
0                  1         Direct               Direct
1                  2      Corporate            Corporate
2                  3      Online TA                TA/TO
3                  4  Offline TA/TO                TA/TO
4                  5  Complementary               Direct

       Market_Segment_ID
count          26.000000
mean           13.500000
std             7.648529
min             1.000000
25%             7.250000
50%            13.500000
75%            19.750000
max            26.000000

In [10]:
# print the number of null values in each column in market_seg
market_seg.isnull().sum()

Market_Segment_ID       0
market_segment          0
distribution_channel    0
dtype: int64

In [11]:
# load dataset5: reservationstatus.csv
res_sts = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Reservation_Status.csv')
display(res_sts .info())
display(res_sts .head())
display(res_sts .describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reservation_ID      3 non-null      int64
 1   reservation_status  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

None

   Reservation_ID reservation_status
0               1          Check-Out
1               2           Canceled
2               3            No-Show

       Reservation_ID
count             3.0
mean              2.0
std               1.0
min               1.0
25%               1.5
50%               2.0
75%               2.5
max               3.0

In [12]:
# print the number of null values in each column in res_sts
res_sts.isnull().sum()

Reservation_ID        0
reservation_status    0
dtype: int64

Observation from booking dataset: data cleansing needed
- There are a total of 119,390 booking records
- Hotel_ID, Market_Segment_ID, Customer_Type_ID, Reservation_ID are foreign keys
- NULL values exist in children, country, agent, company
- reservation_status_date should be date time
- children, agent, and company should be int
- is_repeated_guest and is_canceled should be boolean

Observation from other dataset: No empty values

## 3. Data Cleansing & Preparation

Let's clean the dataset. We'll identify missing values, handle empty rows, correct data types, and prepare the dataset for analysis.

Data cleansing on booking dataset:
1. Derive check-in date
2. Update data type for reservation_status_date
3. Update data type for is_repeated_guest and is_canceled
4. Update data type for children, agent and company
5. Handle NULL values for children, country, agent, company

In [13]:
# 1. Derive check-in date
# combine arrival_date_year, arrival_date_month and arrival_date_day_of_month into strings
booking_date_strings = (
    bookings['arrival_date_year'].astype(str) + '-' +
    bookings['arrival_date_month'].astype(str) + '-' +
    bookings['arrival_date_day_of_month'].astype(str)
)

# convert booking_date_strings to datetime then format as YYYY-MM-DD text
bookings['checkin_date'] = pd.to_datetime(booking_date_strings).dt.strftime('%Y-%m-%d')

# convert that string into a proper pandas datetime object
bookings['checkin_date'] = pd.to_datetime(booking_date_strings)

# verify that first 5 rows of checkin_date
print(bookings['checkin_date'].head())

0   2015-07-01
1   2015-07-01
2   2015-07-01
3   2015-07-01
4   2015-07-01
Name: checkin_date, dtype: datetime64[ns]

In [14]:
# 2. Update data type for reservation_status_date
# convert reservation_status_date to datetime format
bookings['reservation_status_date'] = pd.to_datetime(bookings['reservation_status_date'])

# view the first 5 rows of reservation_status_date
print(bookings['reservation_status_date'].head())

0   2015-07-01
1   2015-07-01
2   2015-07-02
3   2015-07-02
4   2015-07-03
Name: reservation_status_date, dtype: datetime64[ns]

In [15]:
# 3. Update data type for is_repeated_guest and is_canceled
# change datatype from int to boolean
bookings[['is_repeated_guest', 'is_canceled']] = bookings[['is_repeated_guest', 'is_canceled']].astype(bool)

# verify count of is_repeated_guest and is_canceled
print(bookings['is_canceled'].value_counts())
print(bookings['is_repeated_guest'].value_counts())

# confirm values are only false, true
print(bookings['is_canceled'].unique())
print(bookings['is_repeated_guest'].unique())

is_canceled
False    75166
True     44224
Name: count, dtype: int64
is_repeated_guest
False    115580
True       3810
Name: count, dtype: int64
[False  True]
[False  True]

In [16]:
# 4. Update data type for children, agent and company
# change datatype from float to int
bookings[['children', 'agent', 'company']] = bookings[['children', 'agent', 'company']].astype('Int64')

In [17]:
# 5. Handle NULL values for children, country, agent, company
# handle NULL value for children by replacing NULL with 0
bookings['children'] = bookings['children'].fillna(0)

# handle NULL value for country by replacing NULL with UNKNOWN
bookings['country'] = bookings['country'].fillna('Unknown')

# handle NULL value for agent by replacing NULL with 0
bookings['agent'] = bookings['agent'].fillna(0)

# handle NULL value for company by replacing NULL with 0
bookings['company'] = bookings['company'].fillna(0)

In [18]:
# verify null values for each column in booking
bookings.isnull().sum()

Booking_ID                        0
Hotel_ID                          0
Market_Segment_ID                 0
Customer_Type_ID                  0
Reservation_ID                    0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
country                           0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
booking_changes                   0
agent                             0
company                           0
days_in_waiting_list              0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status_date           0
checkin_date                      0
dtype: int64

In [19]:
# check booking data
display(bookings.info())
display(bookings.head())
display(bookings.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 29 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  bool
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119390 non-null  Int64
 15  babies                          119390 non-null  int64
 16  country                         119390 non-null  object
 17  is_repeated_guest               119390 non-null  bool
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           119390 non-null  Int64
 22  company                         119390 non-null  Int64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  datetime64[ns]
 28  checkin_date                    119390 non-null  datetime64[ns]
dtypes: Int64(3), bool(2), datetime64[ns](2), float64(1), int64(19), object(2)
memory usage: 25.2+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,checkin_date
0,1,1,1,1,1,False,342,2015,July,27,...,0,3,0,0,0,0.0,0,0,2015-07-01,2015-07-01
1,2,1,1,1,1,False,737,2015,July,27,...,0,4,0,0,0,0.0,0,0,2015-07-01,2015-07-01
2,3,1,1,1,1,False,7,2015,July,27,...,0,0,0,0,0,75.0,0,0,2015-07-02,2015-07-01
3,4,1,2,1,1,False,13,2015,July,27,...,0,0,304,0,0,75.0,0,0,2015-07-02,2015-07-01
4,5,1,3,1,1,False,14,2015,July,27,...,0,0,240,0,0,98.0,0,1,2015-07-03,2015-07-01

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,checkin_date
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390,119390.000000,...,119390.000000,119390.000000,119390.0,119390.0,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390
unique,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,12,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,August,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,75166,NaN,NaN,13877,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,NaN,104.011416,2016.156554,NaN,27.165173,...,0.137097,0.221124,74.828319,10.775157,2.321149,101.831122,0.062518,0.571363,2016-07-30 00:24:47.883407104,2016-08-28 16:39:45.727447808
min,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.000000,2015.000000,NaN,1.000000,...,0.000000,0.000000,0.0,0.0,0.000000,-6.380000,0.000000,0.000000,2014-10-17 00:00:00,2015-07-01 00:00:00
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,NaN,18.000000,2016.000000,NaN,16.000000,...,0.000000,0.000000,7.0,0.0,0.000000,69.290000,0.000000,0.000000,2016-02-01 00:00:00,2016-03-13 00:00:00
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,NaN,69.000000,2016.000000,NaN,28.000000,...,0.000000,0.000000,9.0,0.0,0.000000,94.575000,0.000000,0.000000,2016-08-07 00:00:00,2016-09-06 00:00:00
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,NaN,160.000000,2017.000000,NaN,38.000000,...,0.000000,0.000000,152.0,0.0,0.000000,126.000000,0.000000,1.000000,2017-02-08 00:00:00,2017-03-18 00:00:00
max,119390.000000,2.000000,26.000000,36.000000,3.000000,NaN,737.000000,2017.000000,NaN,53.000000,...,72.000000,21.000000,535.0,543.0,391.000000,5400.000000,8.000000,5.000000,2017-09-14 00:00:00,2017-08-31 00:00:00
std,34465.068657,0.472181,3.071532,5.250009,0.505913,NaN,106.863097,0.707476,NaN,13.605138,...,1.497437,0.652306,107.141953,53.943884,17.594721,50.535790,0.245291,0.792798,NaN,NaN

### Create df for cleansed data

In [20]:
# create a new df
df = pd.merge(bookings, hotel_type, on='Hotel_ID', how='left')

# merge the rest into new dataset
df = pd.merge(df, market_seg, on='Market_Segment_ID', how='left')
df = pd.merge(df, cust_type, on='Customer_Type_ID', how='left')
df = pd.merge(df, res_sts, on='Reservation_ID', how='left')

In [21]:
df[['children','company','agent']] = df[['children','company','agent']].astype('int64')

In [22]:
# check df data
display(df.info())
display(df.head())
display(df.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  bool
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119390 non-null  int64
 15  babies                          119390 non-null  int64
 16  country                         119390 non-null  object
 17  is_repeated_guest               119390 non-null  bool
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           119390 non-null  int64
 22  company                         119390 non-null  int64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  datetime64[ns]
 28  checkin_date                    119390 non-null  datetime64[ns]
 29  hotel                           119390 non-null  object
 30  market_segment                  119390 non-null  object
 31  distribution_channel            119390 non-null  object
 32  customer_type                   119390 non-null  object
 33  deposit_type                    119390 non-null  object
 34  meal                            119390 non-null  object
 35  reservation_status              119390 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(1), int64(22), object(9)
memory usage: 31.2+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,total_of_special_requests,reservation_status_date,checkin_date,hotel,market_segment,distribution_channel,customer_type,deposit_type,meal,reservation_status
0,1,1,1,1,1,False,342,2015,July,27,...,0,2015-07-01,2015-07-01,Resort Hotel,Direct,Direct,Transient,No Deposit,BB,Check-Out
1,2,1,1,1,1,False,737,2015,July,27,...,0,2015-07-01,2015-07-01,Resort Hotel,Direct,Direct,Transient,No Deposit,BB,Check-Out
2,3,1,1,1,1,False,7,2015,July,27,...,0,2015-07-02,2015-07-01,Resort Hotel,Direct,Direct,Transient,No Deposit,BB,Check-Out
3,4,1,2,1,1,False,13,2015,July,27,...,0,2015-07-02,2015-07-01,Resort Hotel,Corporate,Corporate,Transient,No Deposit,BB,Check-Out
4,5,1,3,1,1,False,14,2015,July,27,...,1,2015-07-03,2015-07-01,Resort Hotel,Online TA,TA/TO,Transient,No Deposit,BB,Check-Out

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,total_of_special_requests,reservation_status_date,checkin_date,hotel,market_segment,distribution_channel,customer_type,deposit_type,meal,reservation_status
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390,119390.000000,...,119390.000000,119390,119390,119390,119390,119390,119390,119390,119390,119390
unique,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,12,NaN,...,NaN,NaN,NaN,2,8,5,4,3,5,3
top,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,August,NaN,...,NaN,NaN,NaN,City Hotel,Online TA,TA/TO,Transient,No Deposit,BB,Check-Out
freq,NaN,NaN,NaN,NaN,NaN,75166,NaN,NaN,13877,NaN,...,NaN,NaN,NaN,79330,56477,97870,89613,104641,92310,75166
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,NaN,104.011416,2016.156554,NaN,27.165173,...,0.571363,2016-07-30 00:24:47.883407104,2016-08-28 16:39:45.727447808,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.000000,2015.000000,NaN,1.000000,...,0.000000,2014-10-17 00:00:00,2015-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,NaN,18.000000,2016.000000,NaN,16.000000,...,0.000000,2016-02-01 00:00:00,2016-03-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,NaN,69.000000,2016.000000,NaN,28.000000,...,0.000000,2016-08-07 00:00:00,2016-09-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,NaN,160.000000,2017.000000,NaN,38.000000,...,1.000000,2017-02-08 00:00:00,2017-03-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,119390.000000,2.000000,26.000000,36.000000,3.000000,NaN,737.000000,2017.000000,NaN,53.000000,...,5.000000,2017-09-14 00:00:00,2017-08-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,34465.068657,0.472181,3.071532,5.250009,0.505913,NaN,106.863097,0.707476,NaN,13.605138,...,0.792798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# remove duplicate fields
df = df.drop(columns=['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month','Hotel_ID', 'Market_Segment_ID', 'Customer_Type_ID', 'Reservation_ID'
])

In [24]:
# create new column for total_night and revenue
# booked room revenue per booking = price per night × number of nights
df['total_nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
df['room_revenue'] = df['adr'].clip(lower=0) * df['total_nights']

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   is_canceled                     119390 non-null  bool
 2   lead_time                       119390 non-null  int64
 3   arrival_date_week_number        119390 non-null  int64
 4   stays_in_weekend_nights         119390 non-null  int64
 5   stays_in_week_nights            119390 non-null  int64
 6   adults                          119390 non-null  int64
 7   children                        119390 non-null  int64
 8   babies                          119390 non-null  int64
 9   country                         119390 non-null  object
 10  is_repeated_guest               119390 non-null  bool
 11  previous_cancellations          119390 non-null  int64
 12  previous_bookings_not_canceled  119390 non-null  int64
 13  booking_changes                 119390 non-null  int64
 14  agent                           119390 non-null  int64
 15  company                         119390 non-null  int64
 16  days_in_waiting_list            119390 non-null  int64
 17  adr                             119390 non-null  float64
 18  required_car_parking_spaces     119390 non-null  int64
 19  total_of_special_requests       119390 non-null  int64
 20  reservation_status_date         119390 non-null  datetime64[ns]
 21  checkin_date                    119390 non-null  datetime64[ns]
 22  hotel                           119390 non-null  object
 23  market_segment                  119390 non-null  object
 24  distribution_channel            119390 non-null  object
 25  customer_type                   119390 non-null  object
 26  deposit_type                    119390 non-null  object
 27  meal                            119390 non-null  object
 28  reservation_status              119390 non-null  object
 29  total_nights                    119390 non-null  int64
 30  room_revenue                    119390 non-null  float64
dtypes: bool(2), datetime64[ns](2), float64(2), int64(17), object(8)
memory usage: 26.6+ MB

### Export data to new CSV file

In [26]:
# export df into CSV file
#df.to_csv('bookings_final.csv', index=False)

#from google.colab import files
#files.download('bookings_final.csv')

In [27]:
# Final step of data cleansing: no nulls remain, so use standard integer types
int_cols = ['children', 'agent', 'company']
assert df[int_cols].isna().sum().sum() == 0
df[int_cols] = df[int_cols].astype('int64')

## 4. Visualization for Research Objective

In [28]:
import warnings; warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt, matplotlib.ticker as mtick
from matplotlib.colors import LinearSegmentedColormap
from scipy.stats import chi2_contingency

# ---- Chart style: one validated palette, recessive grid, no dual axes ----
BLUE, ORANGE, AQUA = '#2a78d6', '#eb6834', '#1baf7a'          # categorical slots 1–3
INK, INK2, MUTED   = '#0b0b0b', '#52514e', '#8a8984'
CONTEXT = '#c9c7c0'                                            # neutral bars for volume / context
GRID, SURFACE = '#e6e5e1', '#fcfcfb'
HOTEL_COLORS = {'City Hotel': BLUE, 'Resort Hotel': ORANGE}
SEQ = LinearSegmentedColormap.from_list('seq_blue',
        ['#cde2fb', '#9ec5f4', '#6da7ec', '#3987e5', '#256abf', '#184f95', '#0d366b'])

plt.rcParams.update({
    'figure.facecolor': SURFACE, 'axes.facecolor': SURFACE, 'savefig.facecolor': SURFACE,
    'axes.edgecolor': GRID, 'axes.labelcolor': INK2, 'xtick.color': INK2, 'ytick.color': INK2,
    'text.color': INK, 'axes.titlecolor': INK, 'axes.titlesize': 11, 'axes.titleweight': 'bold',
    'axes.titlelocation': 'left', 'axes.spines.top': False, 'axes.spines.right': False,
    'axes.grid': True, 'grid.color': GRID, 'grid.linewidth': 0.8, 'axes.axisbelow': True,
    'font.size': 10, 'legend.frameon': False, 'figure.dpi': 110, 'lines.linewidth': 2,
    'xtick.major.size': 0, 'ytick.major.size': 0})
PCT = mtick.PercentFormatter(1.0, decimals=0)
THOU = mtick.FuncFormatter(lambda v, _: f'{v:,.0f}')

def suptitle(fig, text, sub=None, gap=1.0):
    # Title + subtitle anchored in inches from the top, so they never collide with the plot
    H = fig.get_figheight()
    fig.text(0.01, 1 - 0.10 / H, text, ha='left', va='top', fontsize=13, fontweight='bold')
    if sub: fig.text(0.01, 1 - 0.38 / H, sub, ha='left', va='top', fontsize=9.5, color=INK2)
    fig.subplots_adjust(top=1 - gap / H)

In [29]:
# Source: the cleansed DataFrame `df` from the data-cleansing section of this notebook.
# The cleansing step already created every derived column used below (bands, flags, arrival fields),
# so this cell only checks they are present. Arrival-period fields come from checkin_date.
REQUIRED = ['is_canceled', 'checkin_date', 'hotel', 'market_segment', 'distribution_channel', 'customer_type',
            'deposit_type', 'meal', 'reservation_status', 'arrival_month', 'arrival_week', 'arrival_mname',
            'total_nights', 'kids', 'lead_band', 'stay_band', 'changes_band', 'requests_band', 'wait_band',
            'waited', 'party', 'prev_cancel_flag', 'prev_stay_flag', 'has_agent', 'has_company', 'country_prt']
missing = [c for c in REQUIRED if c not in df.columns]
assert not missing, f'These columns are missing from df — re-run the data-cleansing section: {missing}'

# Category orders, used to sort chart axes (must match the labels created during cleansing)
MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
LEAD  = ['0–7', '8–30', '31–90', '91–180', '181–365', '366+']
STAY  = ['0', '1', '2–3', '4–7', '8–14', '15+']
CHG   = ['0', '1', '2', '3+']
REQ   = ['0', '1', '2', '3+']
WAIT  = ['0', '1–7', '8–30', '31–90', '91+']
PARTY = ['Solo adult', 'Couple (2 adults)', '3+ adults', 'With children', 'No adults / unknown']

# 7 bookings carry an 'Undefined' segment/channel — excluded from segment-level views
seg = df[(df['market_segment'] != 'Undefined') & (df['distribution_channel'] != 'Undefined')].copy()

BASE = df['is_canceled'].mean()
print(f"Bookings: {len(df):,}   Cancelled + no-show: {df['is_canceled'].sum():,}   Baseline rate: {BASE:.2%}")
print(df['reservation_status'].value_counts().to_string())

AssertionError: These columns are missing from df — re-run the data-cleansing section: ['arrival_month', 'arrival_week', 'arrival_mname', 'kids', 'lead_band', 'stay_band', 'changes_band', 'requests_band', 'wait_band', 'waited', 'party', 'prev_cancel_flag', 'prev_stay_flag', 'has_agent', 'has_company', 'country_prt']

In [ ]:
def rate_table(data, col, order=None):
    t = data.groupby(col, observed=True)['is_canceled'].agg(bookings='size', cancellations='sum')
    t['cancel_rate'] = t['cancellations'] / t['bookings']
    if order is not None:
        t = t.reindex([o for o in order if o in t.index])
    return t

def baseline_v(ax, label=True, y=None):
    ax.axvline(BASE, color=INK2, lw=1, ls=(0, (4, 3)), zorder=3)
    if label:
        ax.text(BASE, ax.get_ylim()[1] if y is None else y, f' overall {BASE:.1%}',
                color=INK2, fontsize=8.5, va='bottom', ha='left')

def baseline_h(ax, label=True):
    ax.axhline(BASE, color=INK2, lw=1, ls=(0, (4, 3)), zorder=3)
    if label:
        ax.text(ax.get_xlim()[1], BASE, f'overall {BASE:.1%} ', color=INK2, fontsize=8.5,
                va='bottom', ha='right')

def volume_rate_panel(data, col, title, sub=None, order=None):
    # Two aligned panels (one measure each, no dual axis): volume as context, rate as the story
    t = rate_table(data, col, order)
    if order is None:
        t = t.sort_values('cancel_rate')
    y = np.arange(len(t))
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(11, 0.5 * len(t) + 1.9), sharey=True,
                                 gridspec_kw={'width_ratios': [1, 1.25], 'wspace': 0.12})
    a1.barh(y, t['bookings'], color=CONTEXT, height=0.62)
    a1.set_yticks(y, t.index); a1.set_title('Bookings'); a1.xaxis.set_major_formatter(THOU); a1.xaxis.set_major_locator(mtick.MaxNLocator(4))
    a1.set_xlim(0, t['bookings'].max() * 1.28); a1.grid(axis='y', visible=False)
    for yi, v in zip(y, t['bookings']):
        a1.text(v, yi, f' {v:,}', va='center', fontsize=8.5, color=INK2)
    a2.barh(y, t['cancel_rate'], color=BLUE, height=0.62)
    a2.set_title('Cancellation rate'); a2.xaxis.set_major_formatter(PCT)
    a2.set_xlim(0, max(t['cancel_rate'].max(), BASE) * 1.2); a2.grid(axis='y', visible=False)
    for yi, v in zip(y, t['cancel_rate']):
        a2.text(v, yi, f' {v:.1%}', va='center', fontsize=8.5, color=INK)
    a2.set_ylim(-0.6, len(t) - 0.4)
    baseline_v(a2, y=len(t) - 0.45)
    suptitle(fig, title, sub)
    plt.show()
    return t

In [ ]:
# Validate the target: is_canceled should be 1 exactly for Canceled and No-Show
check = pd.crosstab(df['reservation_status'], df['is_canceled'], margins=True)
display(check)

expected = df['reservation_status'].isin(['Canceled', 'No-Show']).astype(int)
mismatches = (df['is_canceled'] != expected).sum()
print(f'Mismatches between is_canceled and reservation_status: {mismatches}')

### RO1 — Volumes and cancellation rates by hotel, arrival period, market segment and channel

In [ ]:
# 1.1 Hotel type
t11 = volume_rate_panel(df, 'hotel', '1.1  City Hotel carries two-thirds of bookings and the higher cancellation rate',
                        'Bookings and cancellation rate (incl. no-shows) by hotel type')
t11

Hotel booking despite having more bookings also had more cancellation rates

In [ ]:
# 1.2 Arrival period — monthly trend per hotel (two stacked panels share the time axis, each with its own measure)
m = (df.groupby(['arrival_month', 'hotel'])['is_canceled'].agg(bookings='size', rate='mean').reset_index())
m['x'] = m['arrival_month'].dt.to_timestamp()
fig, (a1, a2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True, gridspec_kw={'hspace': 0.18})
for h, c in HOTEL_COLORS.items():
    s = m[m['hotel'] == h]
    a1.plot(s['x'], s['bookings'], color=c, marker='o', ms=4, label=h)
    a2.plot(s['x'], s['rate'], color=c, marker='o', ms=4, label=h)
    a1.text(s['x'].iloc[-1], s['bookings'].iloc[-1], f'  {h}', color=INK, va='center', fontsize=9)
    a2.text(s['x'].iloc[-1], s['rate'].iloc[-1], f'  {h}', color=INK, va='center', fontsize=9)
a1.set_title('Bookings by arrival month'); a1.yaxis.set_major_formatter(THOU); a1.legend(loc='upper left')
a2.set_title('Cancellation rate by arrival month'); a2.yaxis.set_major_formatter(PCT); a2.set_ylim(0, 0.6)
a2.set_xlim(m['x'].min() - pd.Timedelta(days=15), m['x'].max() + pd.Timedelta(days=80))
baseline_h(a2, label=False)
suptitle(fig, '1.2  City Hotel cancelled more than Resort in almost every month until mid-2017',
         'Monthly arrivals, Jul 2015 – Aug 2017; dashed line = overall rate')
plt.show()

Cancellation rate for city hotel is consistently always above average (37%)

In [ ]:
# 1.3 Seasonality — cancellation rate by calendar month of arrival, all years pooled
s = df.groupby(['arrival_mname', 'hotel'], observed=True)['is_canceled'].mean().unstack()
fig, ax = plt.subplots(figsize=(11, 4))
for h, c in HOTEL_COLORS.items():
    ax.plot(MONTHS, s[h], color=c, marker='o', ms=5, label=h)
    ax.text(11.15, s[h].iloc[-1], h, color=INK, va='center', fontsize=9)
ax.yaxis.set_major_formatter(PCT); ax.set_ylim(0, 0.6); ax.set_xlim(-0.3, 12.4)
baseline_h(ax, label=False); ax.legend(loc='lower left', ncol=2)
suptitle(fig, '1.3  Summer arrivals cancel more at the Resort; City risk is high year-round',
         'Cancellation rate by calendar month of arrival (2015–2017 pooled)')
plt.show()

Cancellation rate for city is all year round and not seasonal

In [ ]:
# 1.4 Market segment and 1.5 distribution channel
t14 = volume_rate_panel(seg, 'market_segment', '1.4  Groups and Online TA drive cancellation volume',
                        'Bookings and cancellation rate by market segment')
t15 = volume_rate_panel(seg, 'distribution_channel', '1.5  TA/TO is 82% of bookings and cancels at 41%',
                        'Bookings and cancellation rate by distribution channel')

Market segment:

Groups booking has by far the highest rate by far (every 6 in 10 group bookings were cancelled). Direct, Corporate and Complementary bookings have lesser cancellation rate.


Distribution channel:

Although TA/TO bring in the most booking (82%), cancellation rate is also above average. Cancellation rate for direct bookings are the lowest

In [ ]:
# 1.6 Segment x hotel heatmap — rate with volume annotated
piv_r = seg.pivot_table(index='market_segment', columns='hotel', values='is_canceled', aggfunc='mean')
piv_n = seg.pivot_table(index='market_segment', columns='hotel', values='is_canceled', aggfunc='size')
order = piv_n.sum(axis=1).sort_values(ascending=False).index
piv_r, piv_n = piv_r.loc[order], piv_n.loc[order]
fig, ax = plt.subplots(figsize=(7.5, 5.2))
im = ax.imshow(piv_r.values, cmap=SEQ, vmin=0, vmax=0.7, aspect='auto')
ax.set_xticks(range(piv_r.shape[1]), piv_r.columns); ax.set_yticks(range(len(order)), order)
ax.grid(False); [sp.set_visible(False) for sp in ax.spines.values()]
for i in range(piv_r.shape[0]):
    for j in range(piv_r.shape[1]):
        r, n = piv_r.iat[i, j], piv_n.iat[i, j]
        if pd.notna(r):
            ax.text(j, i, f'{r:.0%}\nn={int(n):,}', ha='center', va='center', fontsize=8.5,
                    color='white' if r > 0.4 else INK)
cb = fig.colorbar(im, ax=ax, format=PCT, shrink=0.8); cb.outline.set_visible(False); cb.set_label('Cancellation rate')
suptitle(fig, '1.6  Segment risk differs by hotel', 'Cancellation rate by market segment × hotel; segments ordered by volume')
plt.show()

Cancellation rate for market segment by hotel is different
- City hotel: Group & Offline TA/TO
- Resort hotel: Group & Online TA

In [ ]:
# 1.7 Segment x channel — does the booking channel add anything beyond the segment?
main_share = (seg.groupby('market_segment')['distribution_channel']
                 .agg(lambda s: s.value_counts(normalize=True).iloc[0]).sort_values(ascending=False))
print('Share of each segment booked through its main channel:')
print(main_share.map('{:.1%}'.format).to_string(), '\n')

sc = seg.groupby(['market_segment', 'distribution_channel'])['is_canceled'].agg(bookings='size', cancel_rate='mean').reset_index()
sc = sc[sc['bookings'] >= 200].copy()                       # combinations with enough bookings to compare
seg_order = seg['market_segment'].value_counts().index
sc['seg_rank'] = sc['market_segment'].map({s_: i for i, s_ in enumerate(seg_order)})
sc = sc.sort_values(['seg_rank', 'bookings'], ascending=[False, True])
labels = [f"{a} · {b}   (n={n:,})" for a, b, n in zip(sc['market_segment'], sc['distribution_channel'], sc['bookings'])]
colors = [BLUE if s_ == 'Groups' else CONTEXT for s_ in sc['market_segment']]
fig, ax = plt.subplots(figsize=(10.5, 0.42 * len(sc) + 1.8))
y = np.arange(len(sc))
ax.barh(y, sc['cancel_rate'], color=colors, height=0.62)
for yi, v in zip(y, sc['cancel_rate']):
    ax.text(v, yi, f' {v:.0%}', va='center', fontsize=8.5)
ax.set_yticks(y, labels); ax.xaxis.set_major_formatter(PCT); ax.set_xlim(0, 0.8); ax.grid(axis='y', visible=False)
baseline_v(ax, y=len(sc) - 0.45)
suptitle(fig, '1.7  Channel mostly mirrors segment — except Groups, where agent-booked groups cancel most',
         'Cancellation rate by market segment · distribution channel (combinations with ≥200 bookings); Groups highlighted')
fig.subplots_adjust(left=0.36); plt.show()

Observation
1. City Hotel has the higher cancellation rate compared to Resort Hotel
2. Most of the cancellation come from GROUP bookings via TA/TO
3. Bookings made through TA/TO account for highest cancellation rate

### RO2 — Booking characteristics associated with cancellation

Which characteristics of a booking with increase the risk of booking cancellation

In [ ]:
# 2.1 Lead time — volume and rate per lead-time band, by hotel
lt = df.groupby(['lead_band', 'hotel'], observed=True)['is_canceled'].agg(bookings='size', rate='mean').reset_index()
fig, (a1, a2) = plt.subplots(1, 2, figsize=(12, 4.3), gridspec_kw={'wspace': 0.22})
x = np.arange(len(LEAD)); w = 0.38
for k, (h, c) in enumerate(HOTEL_COLORS.items()):
    s = lt[lt['hotel'] == h].set_index('lead_band').reindex(LEAD)
    a1.bar(x + (k - 0.5) * (w + 0.02), s['bookings'], width=w, color=c, label=h)
    a2.plot(x, s['rate'], color=c, marker='o', ms=6, label=h)
a1.set_xticks(x, LEAD); a1.set_xlabel('Lead time (days)'); a1.yaxis.set_major_formatter(THOU)
a1.set_title('Bookings'); a1.grid(axis='x', visible=False); a1.legend()
a2.set_xticks(x, LEAD); a2.set_xlabel('Lead time (days)'); a2.yaxis.set_major_formatter(PCT)
a2.set_ylim(0, 0.8); a2.set_title('Cancellation rate'); baseline_h(a2); a2.legend(loc='upper left')
suptitle(fig, '2.1  Cancellation risk climbs steadily with lead time',
         'Bookings and cancellation rate by days between booking and arrival')
plt.show()

Observation: The more lead time for a booking, the more likely it is to be cancelled.

In [ ]:
# 2.2 Small multiples — cancellation rate by six booking characteristics
panels = [('deposit_type', 'Deposit type', None), ('customer_type', 'Customer type', None),
          ('stay_band', 'Length of stay (nights)', STAY), ('party', 'Party composition', PARTY),
          ('changes_band', 'Booking changes', CHG), ('requests_band', 'Special requests', REQ)]
fig, axes = plt.subplots(2, 3, figsize=(15, 8.8), gridspec_kw={'hspace': 0.5, 'wspace': 0.16})
for ax, (col, title, order) in zip(axes.ravel(), panels):
    t = rate_table(df, col, order)
    if order is None: t = t.sort_values('cancel_rate', ascending=False)
    labels = [f'{str(i).replace(" (2 adults)", "").replace("No adults / unknown", "No adults").replace("With children", "Children")}\nn={n:,}'
              for i, n in zip(t.index, t['bookings'])]
    xx = np.arange(len(t))
    ax.bar(xx, t['cancel_rate'], color=BLUE, width=0.62)
    for xi, v in zip(xx, t['cancel_rate']):
        ax.text(xi, v + 0.015, f'{v:.0%}', ha='center', fontsize=8.5)
    ax.set_xticks(xx, labels, fontsize=7.5 if len(t) > 4 else 8)
    ax.set_ylim(0, 1.08); ax.yaxis.set_major_formatter(PCT); ax.set_title(title); ax.grid(axis='x', visible=False)
    baseline_h(ax, label=False)
suptitle(fig, '2.2  Non-refundable deposits, no special requests and no booking changes mark high-risk bookings',
         'Cancellation rate by characteristic (dashed line = overall rate; n = bookings)')
plt.show()

Insights:
- "Non Refund" bookings account to 99% cancellation rate
- Bookings with changes and special request are more committed

In [ ]:
# 2.3 Strength of association — Cramér's V for every candidate characteristic
def cramers_v(x, y):
    ct = pd.crosstab(x, y)
    chi2 = chi2_contingency(ct, correction=False)[0]
    n = ct.values.sum(); r, k = ct.shape
    return np.sqrt(chi2 / (n * (min(r, k) - 1)))

cands = {'Deposit type': 'deposit_type', 'Lead time band': 'lead_band', 'Market segment': 'market_segment',
         'Special requests': 'requests_band', 'Distribution channel': 'distribution_channel',
         'Customer type': 'customer_type', 'Booking changes': 'changes_band', 'Hotel type': 'hotel',
         'Previous cancellation': 'prev_cancel_flag', 'Length of stay': 'stay_band', 'Party composition': 'party',
         'Waiting list band': 'wait_band', 'Repeat guest': 'is_repeated_guest', 'Meal plan': 'meal',
         'Arrival month': 'arrival_mname', 'Has agent': 'has_agent',
         'Car parking requested*': 'required_car_parking_spaces', 'Country = PRT*': None}
rows = []
for label, col in cands.items():
    col = col or 'country_prt'
    x = df[col] if col != 'required_car_parking_spaces' else (df[col] > 0).astype(int)
    rows.append((label, cramers_v(x, df['is_canceled'])))
cv = pd.DataFrame(rows, columns=['feature', 'cramers_v']).sort_values('cramers_v')
fig, ax = plt.subplots(figsize=(9, 6.6))
cols = [CONTEXT if f.endswith('*') else BLUE for f in cv['feature']]
ax.barh(cv['feature'], cv['cramers_v'], color=cols, height=0.62)
for yi, v in enumerate(cv['cramers_v']):
    ax.text(v, yi, f' {v:.2f}', va='center', fontsize=8.5)
ax.set_xlim(0, cv['cramers_v'].max() * 1.15); ax.grid(axis='y', visible=False); ax.set_xlabel("Cramér's V (0 = none, 1 = perfect)")
suptitle(fig, '2.3  Deposit type, lead time and market segment are the strongest single signals',
         "Association with cancellation (Cramér's V). * grey = recorded at/after arrival, excluded from the model")
fig.subplots_adjust(left=0.25); plt.show()

Deposit type has the strongest unadjusted association with cancellation in this set (Cramér's V = 0.481).

In [ ]:
# 2.4 Non-refundable cancellations — which segments and channels do they come from?
nr = df[(df['is_canceled'] == 1) & (df['deposit_type'] == 'Non Refund')]
ct = pd.crosstab(nr['market_segment'], nr['distribution_channel'])
ct = ct.loc[ct.sum(axis=1).sort_values().index]                       # biggest segment at the top
CHANNEL_COLORS = {'TA/TO': BLUE, 'Direct': ORANGE, 'Corporate': AQUA, 'GDS': '#eda100'}   # fixed colour per channel
channels = [c for c in CHANNEL_COLORS if c in ct.columns]
ct = ct[channels]
total = ct.sum(axis=1)

fig, ax = plt.subplots(figsize=(10.5, 0.55 * len(ct) + 2.2))
left = np.zeros(len(ct))
for ch in channels:
    ax.barh(ct.index, ct[ch], left=left, color=CHANNEL_COLORS[ch], height=0.6, label=ch,
            edgecolor=SURFACE, linewidth=1.5)                           # thin gap between stacked pieces
    left += ct[ch].values
for y, (seg_name, t) in enumerate(total.items()):
    top_ch = ct.loc[seg_name].idxmax()
    ax.text(t, y, f'  {t:,}  ({ct.loc[seg_name, top_ch] / t:.0%} {top_ch})', va='center', fontsize=9, color=INK2)
ax.xaxis.set_major_formatter(THOU); ax.set_xlim(0, total.max() * 1.35); ax.grid(axis='y', visible=False)
ax.set_xlabel('Cancelled bookings with a Non Refund deposit')
ax.legend(title='Distribution channel', loc='lower right')
suptitle(fig, f'2.4  {len(nr):,} non-refundable cancellations — almost all Groups and Offline TA/TO via travel agents',
         'Cancelled bookings with deposit type = Non Refund: market segment (bars) split by distribution channel (colours)')
plt.show()
ct.assign(Total=total).sort_values('Total', ascending=False)

99% of the group cancellation are for bookings made via TA/TO and not by individual guest

### RO3 — Waiting-list days and cancellation

Any correlation between waiting list days and cancellation

In [ ]:
# 3.1 Raw cancellation rate by waiting-list band
t31 = rate_table(df, 'wait_band', WAIT)
fig, ax = plt.subplots(figsize=(9, 4))
xx = np.arange(len(t31))
ax.bar(xx, t31['cancel_rate'], color=BLUE, width=0.6)
for xi, (v, n) in enumerate(zip(t31['cancel_rate'], t31['bookings'])):
    ax.text(xi, v + 0.015, f'{v:.0%}', ha='center', fontsize=9)
ax.set_xticks(xx, [f'{b} days\nn={n:,}' for b, n in zip(t31.index, t31['bookings'])])
ax.set_ylim(0, 1); ax.yaxis.set_major_formatter(PCT); ax.grid(axis='x', visible=False); baseline_h(ax, label=False)
suptitle(fig, f"3.1  Only {df['waited'].mean():.1%} of bookings ever waited — but they cancel far more often",
         'Cancellation rate by days on the waiting list (dashed line = overall rate)')
plt.show()

print('Composition of waiting-list bookings (deposit type):')
print(df.loc[df['waited'] == 1, 'deposit_type'].value_counts(normalize=True).round(3).to_string())

 115K bookings that were cancelled did not had any wait time

In [ ]:
# 3.2 Stratified comparison — waited vs not, within hotel x deposit type
strata = df[df['deposit_type'] != 'Refundable'].copy()
strata['stratum'] = strata['hotel'].str.replace(' Hotel', '') + ' · ' + strata['deposit_type']
g = strata.groupby(['stratum', 'waited'])['is_canceled'].agg(['size', 'mean']).unstack()
g = g[(g[('size', 1)] >= 30)]                                    # keep strata with enough waited bookings
fig, ax = plt.subplots(figsize=(10, 3.8))
y = np.arange(len(g))
for y_, (_, r) in zip(y, g.iterrows()):
    ax.plot([r[('mean', 0)], r[('mean', 1)]], [y_, y_], color=GRID, lw=3, zorder=1)
ax.scatter(g[('mean', 0)], y, color=BLUE, s=70, zorder=3, label='Did not wait', edgecolor=SURFACE, linewidth=2)
ax.scatter(g[('mean', 1)], y, color=ORANGE, s=70, zorder=2, label='Waited ≥1 day', edgecolor=SURFACE, linewidth=2)
for y_, (_, r) in zip(y, g.iterrows()):
    ax.text(1.03, y_, f"{r[('mean', 0)]:.0%} → {r[('mean', 1)]:.0%}  (n waited = {int(r[('size', 1)]):,})", va='center', fontsize=8.5, color=INK2)
ax.set_yticks(y, g.index); ax.set_xlim(0, 1.42); ax.set_ylim(-0.5, len(g) - 0.5); ax.xaxis.set_major_formatter(PCT)
ax.set_xticks(np.arange(0, 1.01, 0.2)); ax.grid(axis='y', visible=False); ax.legend(loc='lower left', ncol=2, bbox_to_anchor=(0, 1.0))
suptitle(fig, '3.2  Within the same hotel and deposit type, waiting-list bookings do not cancel more',
         'Cancellation rate for bookings that did / did not wait, by stratum — the raw gap in 3.1 comes from non-refundable allocations', gap=1.3)
fig.subplots_adjust(left=0.2); plt.show()

- Resort properties (No Deposit): The cancellation rate drops significantly from 25% for customers who did not wait to 5% for customers who waited at least one day.
- City properties (Non Refund): Both groups show a 100% cancellation rate, indicating no difference regardless of waitlist status
- City properties (No Deposit): The cancellation rate decreases from 31% for those who did not wait to 23% for those who waited.

In [ ]:
# 3.3 Logistic regression — odds ratio for each waiting-list band, unadjusted vs adjusted
import statsmodels.formula.api as smf
mdl = seg.copy()
mdl['wait_band'] = mdl['wait_band'].astype(str)
for c in ['lead_band', 'stay_band', 'party', 'requests_band', 'arrival_mname']:
    mdl[c] = mdl[c].astype(str)
ref = "C(wait_band, Treatment('0'))"
f_un = f"is_canceled ~ {ref}"
f_adj = (f"is_canceled ~ {ref} + C(hotel) + C(market_segment) + C(deposit_type) + C(customer_type) "
         "+ C(lead_band) + C(stay_band) + C(party) + C(requests_band) + C(arrival_mname) "
         "+ is_repeated_guest + prev_cancel_flag")
res = {}
for name, f in [('Unadjusted', f_un), ('Adjusted', f_adj)]:
    fit = smf.logit(f, data=mdl).fit(disp=0, maxiter=300)
    ci = fit.conf_int()
    keep = [i for i in fit.params.index if i.startswith(ref)]
    res[name] = pd.DataFrame({'OR': np.exp(fit.params[keep]).values, 'lo': np.exp(ci.loc[keep, 0]).values,
                              'hi': np.exp(ci.loc[keep, 1]).values, 'p': fit.pvalues[keep].values},
                             index=[k.split('[T.')[1].rstrip(']') for k in keep]).reindex(WAIT[1:])
fig, ax = plt.subplots(figsize=(9.5, 4))
y = np.arange(len(WAIT) - 1)
for k, (name, c) in enumerate([('Unadjusted', CONTEXT), ('Adjusted', BLUE)]):
    r = res[name]; yy = y + (0.15 if k == 0 else -0.15)
    ax.errorbar(r['OR'], yy, xerr=[r['OR'] - r['lo'], r['hi'] - r['OR']], fmt='o', color=c, ms=7,
                capsize=0, elinewidth=2, label=name, markeredgecolor=SURFACE)
ax.axvline(1, color=INK2, lw=1)
ax.set_xscale('log'); ax.xaxis.set_major_formatter(mtick.FuncFormatter(lambda v, _: f'{v:g}'))
ax.set_yticks(y, [f'{b} days' for b in WAIT[1:]]); ax.invert_yaxis(); ax.grid(axis='y', visible=False)
ax.set_xlabel('Odds ratio vs. no waiting (log scale, 95% CI)'); ax.legend(loc='lower right')
suptitle(fig, '3.3  Once booking profile is controlled for, waiting-list effects shrink and point in mixed directions',
         'Logistic regression: odds of cancellation by waiting-list band, before vs after controlling for booking profile')
plt.show()
pd.concat(res, axis=1).round(3)

Waiting list has no consistent effect on cancellation

### RO4 — Repeat guests and previous booking history by market segment

Validate whether returning guests cancel their bookings less often

In [ ]:
# 4.1 Repeat-guest share and booking history by segment (three related shares on one % axis)
h = seg.groupby('market_segment').agg(bookings=('is_canceled', 'size'), repeat=('is_repeated_guest', 'mean'),
                                       prev_stay=('prev_stay_flag', 'mean'), prev_cancel=('prev_cancel_flag', 'mean'))
h = h.sort_values('repeat')
fig, ax = plt.subplots(figsize=(10.5, 5.6))
y = np.arange(len(h)); w = 0.26
series = [('repeat', 'Flagged repeat guest', BLUE), ('prev_stay', 'Has ≥1 previous completed stay', ORANGE),
          ('prev_cancel', 'Has ≥1 previous cancellation', AQUA)]
for k, (col, lab, c) in enumerate(series):
    ax.barh(y + (1 - k) * (w + 0.02), h[col], height=w, color=c, label=lab)
for yi, (v, n) in enumerate(zip(h['repeat'], h['bookings'])):
    ax.text(max(h.loc[h.index[yi], ['repeat', 'prev_stay', 'prev_cancel']]) + 0.01, yi, f'{v:.1%} repeat · n={n:,}',
            va='center', fontsize=8.5, color=INK2)
ax.set_yticks(y, h.index); ax.xaxis.set_major_formatter(PCT); ax.set_xlim(0, h[['repeat', 'prev_stay']].max().max() * 1.45)
ax.grid(axis='y', visible=False); ax.legend(loc='lower right')
suptitle(fig, '4.1  Corporate, Complementary and Aviation are the loyalty segments; Online TA guests rarely return',
         'Share of bookings by market segment with each repeat-booking indicator')
plt.show()

Complementary, Corporate and Aviation are the loyalty segments: 27–31% of their bookings come from returning guests (business travellers and airline crew return regularly). Online TA guests almost never return (1.1%) even though they're the largest segment.

In [ ]:
# 4.2 Dumbbell — cancellation rate, first-time vs repeat guests, within each segment
d = seg.groupby(['market_segment', 'is_repeated_guest'])['is_canceled'].agg(['size', 'mean']).unstack()
d = d[d[('size', 1)] >= 30].sort_values(('mean', 0))
fig, ax = plt.subplots(figsize=(10, 4.6))
y = np.arange(len(d))
for y_, (_, r) in zip(y, d.iterrows()):
    ax.plot([r[('mean', 0)], r[('mean', 1)]], [y_, y_], color=GRID, lw=3, zorder=1)
ax.scatter(d[('mean', 0)], y, color=BLUE, s=70, zorder=2, label='First-time guest', edgecolor=SURFACE, linewidth=2)
ax.scatter(d[('mean', 1)], y, color=ORANGE, s=70, zorder=2, label='Repeat guest', edgecolor=SURFACE, linewidth=2)
for y_, (_, r) in zip(y, d.iterrows()):
    ax.text(0.92, y_, f"repeat n = {int(r[('size', 1)]):,}", va='center', fontsize=8.5, color=INK2)
ax.set_yticks(y, d.index); ax.set_xlim(0, 1.08); ax.set_xticks(np.arange(0, 0.91, 0.1)); ax.xaxis.set_major_formatter(PCT)
ax.grid(axis='y', visible=False); ax.legend(loc='lower left', ncol=2, bbox_to_anchor=(0, 1.0))
suptitle(fig, '4.2  Repeat guests cancel less in every segment except Groups',
         'Cancellation rate by guest type within market segment (segments with ≥30 repeat bookings)', gap=1.3)
plt.show()

For all market segment (except group) returning guests are less likely to cancel booking

### RO5 — High-volume, high-risk booking profiles

If the hotel only focus on a few types of customer, would cancellation rate
decrease?

NOTE:
- Profile is a combination of hotel + market segment + deposit type and lead-time band e.g., “City · Online TA · No Deposit · booked 6–12 months ahead”. The reason why i didnt include distribution channel as part of the profile its because it didnt move the needle for the share of all cancellations for the top 10 profile
- High-volume + high risk booking profile refer to bookings that have high cancellation rate and booking volume is substential

In [ ]:
pcols = ['hotel', 'market_segment', 'deposit_type', 'lead_band']
prof = seg.groupby(pcols, observed=True)['is_canceled'].agg(bookings='size', cancellations='sum').reset_index()
prof = prof[prof['bookings'] >= 300].copy()
prof['cancel_rate'] = prof['cancellations'] / prof['bookings']
prof['excess'] = prof['bookings'] * (prof['cancel_rate'] - BASE)
prof['profile'] = (prof['hotel'].str.replace(' Hotel', '') + ' · ' + prof['market_segment'] + ' · '
                   + prof['deposit_type'] + ' · ' + prof['lead_band'].astype(str) + 'd')
prof['priority'] = (prof['cancel_rate'] >= 0.5) & (prof['bookings'] >= 1000)
prof = prof.sort_values('excess', ascending=False).reset_index(drop=True)
top = prof[prof['priority']].head(10).copy(); top['rank'] = range(1, len(top) + 1)

# 5.1 Volume vs rate map
fig, ax = plt.subplots(figsize=(11, 6))
o = prof[~prof['priority']]; p = prof[prof['priority']]
ax.scatter(o['bookings'], o['cancel_rate'], s=45, color=CONTEXT, edgecolor=SURFACE, linewidth=1.5, label='Other profiles (≥300 bookings)')
ax.scatter(p['bookings'], p['cancel_rate'], s=70, color=BLUE, edgecolor=SURFACE, linewidth=2, label='Priority: ≥50% rate and ≥1,000 bookings')
for _, r in top.iterrows():
    ax.annotate(str(r['rank']), (r['bookings'], r['cancel_rate']), xytext=(6, 4), textcoords='offset points',
                fontsize=9, fontweight='bold')
ax.axhline(0.5, color=INK2, lw=1, ls=(0, (4, 3))); ax.axvline(1000, color=INK2, lw=1, ls=(0, (4, 3)))
ax.set_xscale('log'); ax.xaxis.set_major_formatter(THOU); ax.yaxis.set_major_formatter(PCT); ax.set_ylim(0, 1.05)
ax.set_xlabel('Bookings in profile (log scale)'); ax.set_ylabel('Cancellation rate'); ax.legend(loc='lower left', bbox_to_anchor=(0, 1.0), ncol=2)
suptitle(fig, f'5.1  {len(p)} profiles combine high risk with high volume',
         'Each dot = hotel × segment × deposit × lead-time profile; numbers match ranks in 5.2', gap=1.3)
plt.show()

In [ ]:
# 5.2 Ranked priority profiles by excess cancellations
t = top.iloc[::-1]
fig, ax = plt.subplots(figsize=(11, 0.48 * len(t) + 1.8))
ax.barh(range(len(t)), t['excess'], color=BLUE, height=0.62)
ax.set_yticks(range(len(t)), [f"{r}. {p}" for r, p in zip(t['rank'], t['profile'])])
for yi, (_, r) in enumerate(t.iterrows()):
    ax.text(r['excess'], yi, f"  {r['excess']:,.0f}   (n={r['bookings']:,}, {r['cancel_rate']:.0%})", va='center', fontsize=8.5, color=INK2)
ax.set_xlim(0, t['excess'].max() * 1.45); ax.xaxis.set_major_formatter(THOU); ax.grid(axis='y', visible=False)
ax.set_xlabel('Excess cancellations vs. overall rate')
suptitle(fig, '5.2  Top priority profiles ranked by excess cancellations', 'Cancellations above the 37% baseline that each profile generates')
fig.subplots_adjust(left=0.38); plt.show()
top[['rank', 'profile', 'bookings', 'cancel_rate', 'excess']].round(3)

In [ ]:
# 5.3 No Deposit profiles above the baseline with ≥1,000 bookings
nd = prof[(prof['deposit_type'] == 'No Deposit') & (prof['bookings'] >= 1000) & (prof['cancel_rate'] > BASE)]
nd = nd.sort_values('excess', ascending=False).head(10).iloc[::-1]
lab = nd['profile'].str.replace(' · No Deposit', '', regex=False)
fig, ax = plt.subplots(figsize=(11, 0.48 * len(nd) + 1.8))
ax.barh(range(len(nd)), nd['excess'], color=BLUE, height=0.62)
ax.set_yticks(range(len(nd)), lab)
for yi, (_, r) in enumerate(nd.iterrows()):
    ax.text(r['excess'], yi, f"  {r['excess']:,.0f}   (n={r['bookings']:,}, {r['cancel_rate']:.0%})", va='center', fontsize=8.5, color=INK2)
ax.set_xlim(0, nd['excess'].max() * 1.45); ax.xaxis.set_major_formatter(THOU); ax.grid(axis='y', visible=False)
ax.set_xlabel('Excess cancellations vs. overall rate')
suptitle(fig, '5.3  Among No Deposit bookings, long-lead Online TA reservations are the main target',
         'No Deposit profiles (hotel · segment · lead time) with ≥1,000 bookings and an above-average rate')
fig.subplots_adjust(left=0.3); plt.show()
nd.iloc[::-1][['profile', 'bookings', 'cancel_rate', 'excess']].round(3)