<a href="https://colab.research.google.com/github/elsiejy/Capstone/blob/main/Capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1: Descriptive Analysis

### 1. Import libraries
Import the libaries into the notebook

In [39]:
# import libraries
import pandas as pd
import numpy as np

# ignore the warnings that may appear
import warnings
warnings.filterwarnings("ignore")

### 2. Import data

Import csv files into the notebook. Here the file is hosted in github thus we will read the file directly from github

In [40]:
# load dataset1: booking.csv
bookings = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Bookings.csv')
display(bookings.info())
display(bookings.head())
display(bookings.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 28 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  int64
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119386 non-null  float64
 15  babies                          119390 non-null  int64
 16  country                         118902 non-null  object
 17  is_repeated_guest               119390 non-null  int64
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           103050 non-null  float64
 22  company                         6797 non-null    float64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(21), object(3)
memory usage: 25.5+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date
0,1,1,1,1,1,0,342,2015,July,27,...,0,0,3,NaN,NaN,0,0.0,0,0,2015-07-01
1,2,1,1,1,1,0,737,2015,July,27,...,0,0,4,NaN,NaN,0,0.0,0,0,2015-07-01
2,3,1,1,1,1,0,7,2015,July,27,...,0,0,0,NaN,NaN,0,75.0,0,0,2015-07-02
3,4,1,2,1,1,0,13,2015,July,27,...,0,0,0,304.0,NaN,0,75.0,0,0,2015-07-02
4,5,1,3,1,1,0,14,2015,July,27,...,0,0,0,240.0,NaN,0,98.0,0,1,2015-07-03

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,...,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,0.370416,104.011416,2016.156554,27.165173,15.798241,...,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,34465.068657,0.472181,3.071532,5.250009,0.505913,0.482918,106.863097,0.707476,13.605138,8.780829,...,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,2015.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,0.000000,18.000000,2016.000000,16.000000,8.000000,...,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,0.000000,69.000000,2016.000000,28.000000,16.000000,...,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,1.000000,160.000000,2017.000000,38.000000,23.000000,...,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,119390.000000,2.000000,26.000000,36.000000,3.000000,1.000000,737.000000,2017.000000,53.000000,31.000000,...,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [41]:
# print the number of null values in each column in booking
bookings.isnull().sum()

Booking_ID                             0
Hotel_ID                               0
Market_Segment_ID                      0
Customer_Type_ID                       0
Reservation_ID                         0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
country                              488
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
booking_changes                        0
agent                              16340
company                           112593
days_in_waiting_list                   0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status_date                0
dtype: int64

In [42]:
# load dataset2: customertype.csv
cust_type = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/CustomerTypes.csv')
display(cust_type.info())
display(cust_type.head())
display(cust_type.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_Type_ID  36 non-null     int64
 1   customer_type     36 non-null     object
 2   deposit_type      36 non-null     object
 3   meal              36 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.3+ KB

None

   Customer_Type_ID customer_type deposit_type meal
0                 1     Transient   No Deposit   BB
1                 2     Transient   No Deposit   FB
2                 3     Transient   No Deposit   HB
3                 4      Contract   No Deposit   BB
4                 5      Contract   No Deposit   HB

       Customer_Type_ID
count         36.000000
mean          18.500000
std           10.535654
min            1.000000
25%            9.750000
50%           18.500000
75%           27.250000
max           36.000000

In [43]:
# print the number of null values in each column in cust_type
cust_type.isnull().sum()

Customer_Type_ID    0
customer_type       0
deposit_type        0
meal                0
dtype: int64

In [44]:
# load dataset3: hotel.csv
hotel_type = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/Hotels.csv')
display(hotel_type.info())
display(hotel_type.head())
display(hotel_type.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Hotel_ID  2 non-null      int64
 1   hotel     2 non-null      object
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

None

   Hotel_ID         hotel
0         1  Resort Hotel
1         2    City Hotel

       Hotel_ID
count  2.000000
mean   1.500000
std    0.707107
min    1.000000
25%    1.250000
50%    1.500000
75%    1.750000
max    2.000000

In [45]:
# print the number of null values in each column in hotel_type
hotel_type.isnull().sum()

Hotel_ID    0
hotel       0
dtype: int64

In [46]:
# load dataset4: marketsegment.csv
market_seg = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/MarketSegments.csv')
display(market_seg.info())
display(market_seg.head())
display(market_seg.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Market_Segment_ID     26 non-null     int64
 1   market_segment        26 non-null     object
 2   distribution_channel  26 non-null     object
dtypes: int64(1), object(2)
memory usage: 756.0+ bytes

None

   Market_Segment_ID market_segment distribution_channel
0                  1         Direct               Direct
1                  2      Corporate            Corporate
2                  3      Online TA                TA/TO
3                  4  Offline TA/TO                TA/TO
4                  5  Complementary               Direct

       Market_Segment_ID
count          26.000000
mean           13.500000
std             7.648529
min             1.000000
25%             7.250000
50%            13.500000
75%            19.750000
max            26.000000

In [47]:
# print the number of null values in each column in market_seg
market_seg.isnull().sum()

Market_Segment_ID       0
market_segment          0
distribution_channel    0
dtype: int64

In [48]:
# load dataset5: reservationstatus.csv
res_sts = pd.read_csv('https://raw.githubusercontent.com/elsiejy/Capstone/refs/heads/main/ReservationStatus.csv')
display(res_sts .info())
display(res_sts .head())
display(res_sts .describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reservation_ID      3 non-null      int64
 1   reservation_status  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

None

   Reservation_ID reservation_status
0               1          Check-Out
1               2           Canceled
2               3            No-Show

       Reservation_ID
count             3.0
mean              2.0
std               1.0
min               1.0
25%               1.5
50%               2.0
75%               2.5
max               3.0

In [49]:
# print the number of null values in each column in res_sts
res_sts.isnull().sum()

Reservation_ID        0
reservation_status    0
dtype: int64

Observation from booking dataset: data cleansing needed
- There are a total of 119,390 booking records
- Hotel_ID, Market_Segment_ID, Customer_Type_ID, Reservation_ID are foreign keys
- NULL values exist in children, country, agent, company
- reservation_status_date should be date time
- children, agent, and company should be int
- is_repeated_guest and is_canceled should be boolean

Observation from other dataset: No empty values

### 3. Data Cleansing & Preparation

Let's clean the dataset. We'll identify missing values, handle empty rows, correct data types, and prepare the dataset for analysis.

Data cleansing on booking dataset:
1. Derive check-in date
2. Update data type for reservation_status_date
3. Update data type for is_repeated_guest and is_canceled
4. Update data type for children, agent and company
5. Handle NULL values for children, country, agent, company

In [50]:
# 1. Derive check-in date
# combine arrival_date_year, arrival_date_month and arrival_date_day_of_month into strings
booking_date_strings = (
    bookings['arrival_date_year'].astype(str) + '-' +
    bookings['arrival_date_month'].astype(str) + '-' +
    bookings['arrival_date_day_of_month'].astype(str)
)

# convert booking_date_strings to datetime then format as YYYY-MM-DD text
bookings['checkin_date'] = pd.to_datetime(booking_date_strings).dt.strftime('%Y-%m-%d')

# convert that string into a proper pandas datetime object
bookings['checkin_date'] = pd.to_datetime(booking_date_strings)

# verify that first 5 rows of checkin_date
print(bookings['checkin_date'].head())

0   2015-07-01
1   2015-07-01
2   2015-07-01
3   2015-07-01
4   2015-07-01
Name: checkin_date, dtype: datetime64[ns]

In [51]:
# 2. Update data type for reservation_status_date
# convert reservation_status_date to datetime format
bookings['reservation_status_date'] = pd.to_datetime(bookings['reservation_status_date'])

# view the first 5 rows of reservation_status_date
print(bookings['reservation_status_date'].head())

0   2015-07-01
1   2015-07-01
2   2015-07-02
3   2015-07-02
4   2015-07-03
Name: reservation_status_date, dtype: datetime64[ns]

In [52]:
# 3. Update data type for is_repeated_guest and is_canceled
# change datatype from int to boolean
bookings[['is_repeated_guest', 'is_canceled']] = bookings[['is_repeated_guest', 'is_canceled']].astype(bool)

# verify count of is_repeated_guest and is_canceled
print(bookings['is_canceled'].value_counts())
print(bookings['is_repeated_guest'].value_counts())

# confirm values are only false, true
print(bookings['is_canceled'].unique())
print(bookings['is_repeated_guest'].unique())

is_canceled
False    75166
True     44224
Name: count, dtype: int64
is_repeated_guest
False    115580
True       3810
Name: count, dtype: int64
[False  True]
[False  True]

In [53]:
# 4. Update data type for children, agent and company
# change datatype from float to int
bookings[['children', 'agent', 'company']] = bookings[['children', 'agent', 'company']].astype('Int64')

In [54]:
# 5. Handle NULL values for children, country, agent, company
# handle NULL value for children by replacing NULL with 0
bookings['children'] = bookings['children'].fillna(0)

# handle NULL value for country by replacing NULL with UNKNOWN
bookings['country'] = bookings['country'].fillna('Unknown')

# handle NULL value for agent by replacing NULL with 0
bookings['agent'] = bookings['agent'].fillna(0)

# handle NULL value for company by replacing NULL with 0
bookings['company'] = bookings['company'].fillna(0)

In [55]:
# verify null values for each column in booking
bookings.isnull().sum()

Booking_ID                        0
Hotel_ID                          0
Market_Segment_ID                 0
Customer_Type_ID                  0
Reservation_ID                    0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
country                           0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
booking_changes                   0
agent                             0
company                           0
days_in_waiting_list              0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status_date           0
checkin_date                      0
dtype: int64

In [56]:
# check booking data
display(bookings.info())
display(bookings.head())
display(bookings.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 29 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  bool
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119390 non-null  Int64
 15  babies                          119390 non-null  int64
 16  country                         119390 non-null  object
 17  is_repeated_guest               119390 non-null  bool
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           119390 non-null  Int64
 22  company                         119390 non-null  Int64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  datetime64[ns]
 28  checkin_date                    119390 non-null  datetime64[ns]
dtypes: Int64(3), bool(2), datetime64[ns](2), float64(1), int64(19), object(2)
memory usage: 25.2+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,checkin_date
0,1,1,1,1,1,False,342,2015,July,27,...,0,3,0,0,0,0.0,0,0,2015-07-01,2015-07-01
1,2,1,1,1,1,False,737,2015,July,27,...,0,4,0,0,0,0.0,0,0,2015-07-01,2015-07-01
2,3,1,1,1,1,False,7,2015,July,27,...,0,0,0,0,0,75.0,0,0,2015-07-02,2015-07-01
3,4,1,2,1,1,False,13,2015,July,27,...,0,0,304,0,0,75.0,0,0,2015-07-02,2015-07-01
4,5,1,3,1,1,False,14,2015,July,27,...,0,0,240,0,0,98.0,0,1,2015-07-03,2015-07-01

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_date,checkin_date
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390,119390.000000,...,119390.000000,119390.000000,119390.0,119390.0,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390
unique,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,12,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,August,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,75166,NaN,NaN,13877,NaN,...,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,NaN,104.011416,2016.156554,NaN,27.165173,...,0.137097,0.221124,74.828319,10.775157,2.321149,101.831122,0.062518,0.571363,2016-07-30 00:24:47.883407104,2016-08-28 16:39:45.727447808
min,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.000000,2015.000000,NaN,1.000000,...,0.000000,0.000000,0.0,0.0,0.000000,-6.380000,0.000000,0.000000,2014-10-17 00:00:00,2015-07-01 00:00:00
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,NaN,18.000000,2016.000000,NaN,16.000000,...,0.000000,0.000000,7.0,0.0,0.000000,69.290000,0.000000,0.000000,2016-02-01 00:00:00,2016-03-13 00:00:00
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,NaN,69.000000,2016.000000,NaN,28.000000,...,0.000000,0.000000,9.0,0.0,0.000000,94.575000,0.000000,0.000000,2016-08-07 00:00:00,2016-09-06 00:00:00
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,NaN,160.000000,2017.000000,NaN,38.000000,...,0.000000,0.000000,152.0,0.0,0.000000,126.000000,0.000000,1.000000,2017-02-08 00:00:00,2017-03-18 00:00:00
max,119390.000000,2.000000,26.000000,36.000000,3.000000,NaN,737.000000,2017.000000,NaN,53.000000,...,72.000000,21.000000,535.0,543.0,391.000000,5400.000000,8.000000,5.000000,2017-09-14 00:00:00,2017-08-31 00:00:00
std,34465.068657,0.472181,3.071532,5.250009,0.505913,NaN,106.863097,0.707476,NaN,13.605138,...,1.497437,0.652306,107.141953,53.943884,17.594721,50.535790,0.245291,0.792798,NaN,NaN

#### Create df for cleansed data

In [57]:
# create a new df
df = pd.merge(bookings, hotel_type, on='Hotel_ID', how='left')

# merge the rest into new dataset
df = pd.merge(df, market_seg, on='Market_Segment_ID', how='left')
df = pd.merge(df, cust_type, on='Customer_Type_ID', how='left')
df = pd.merge(df, res_sts, on='Reservation_ID', how='left')

In [58]:
df[['children','company','agent']] = df[['children','company','agent']].astype('int64')

In [59]:
# check df data
display(df.info())
display(df.head())
display(df.describe(include='all'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Booking_ID                      119390 non-null  int64
 1   Hotel_ID                        119390 non-null  int64
 2   Market_Segment_ID               119390 non-null  int64
 3   Customer_Type_ID                119390 non-null  int64
 4   Reservation_ID                  119390 non-null  int64
 5   is_canceled                     119390 non-null  bool
 6   lead_time                       119390 non-null  int64
 7   arrival_date_year               119390 non-null  int64
 8   arrival_date_month              119390 non-null  object
 9   arrival_date_week_number        119390 non-null  int64
 10  arrival_date_day_of_month       119390 non-null  int64
 11  stays_in_weekend_nights         119390 non-null  int64
 12  stays_in_week_nights            119390 non-null  int64
 13  adults                          119390 non-null  int64
 14  children                        119390 non-null  int64
 15  babies                          119390 non-null  int64
 16  country                         119390 non-null  object
 17  is_repeated_guest               119390 non-null  bool
 18  previous_cancellations          119390 non-null  int64
 19  previous_bookings_not_canceled  119390 non-null  int64
 20  booking_changes                 119390 non-null  int64
 21  agent                           119390 non-null  int64
 22  company                         119390 non-null  int64
 23  days_in_waiting_list            119390 non-null  int64
 24  adr                             119390 non-null  float64
 25  required_car_parking_spaces     119390 non-null  int64
 26  total_of_special_requests       119390 non-null  int64
 27  reservation_status_date         119390 non-null  datetime64[ns]
 28  checkin_date                    119390 non-null  datetime64[ns]
 29  hotel                           119390 non-null  object
 30  market_segment                  119390 non-null  object
 31  distribution_channel            119390 non-null  object
 32  customer_type                   119390 non-null  object
 33  deposit_type                    119390 non-null  object
 34  meal                            119390 non-null  object
 35  reservation_status              119390 non-null  object
dtypes: bool(2), datetime64[ns](2), float64(1), int64(22), object(9)
memory usage: 31.2+ MB

None

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,total_of_special_requests,reservation_status_date,checkin_date,hotel,market_segment,distribution_channel,customer_type,deposit_type,meal,reservation_status
0,1,1,1,1,1,False,342,2015,July,27,...,0,2015-07-01,2015-07-01,Resort Hotel,Direct,Direct,Transient,No Deposit,BB,Check-Out
1,2,1,1,1,1,False,737,2015,July,27,...,0,2015-07-01,2015-07-01,Resort Hotel,Direct,Direct,Transient,No Deposit,BB,Check-Out
2,3,1,1,1,1,False,7,2015,July,27,...,0,2015-07-02,2015-07-01,Resort Hotel,Direct,Direct,Transient,No Deposit,BB,Check-Out
3,4,1,2,1,1,False,13,2015,July,27,...,0,2015-07-02,2015-07-01,Resort Hotel,Corporate,Corporate,Transient,No Deposit,BB,Check-Out
4,5,1,3,1,1,False,14,2015,July,27,...,1,2015-07-03,2015-07-01,Resort Hotel,Online TA,TA/TO,Transient,No Deposit,BB,Check-Out

,Booking_ID,Hotel_ID,Market_Segment_ID,Customer_Type_ID,Reservation_ID,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,...,total_of_special_requests,reservation_status_date,checkin_date,hotel,market_segment,distribution_channel,customer_type,deposit_type,meal,reservation_status
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390,119390.000000,...,119390.000000,119390,119390,119390,119390,119390,119390,119390,119390,119390
unique,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,12,NaN,...,NaN,NaN,NaN,2,8,5,4,3,5,3
top,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,August,NaN,...,NaN,NaN,NaN,City Hotel,Online TA,TA/TO,Transient,No Deposit,BB,Check-Out
freq,NaN,NaN,NaN,NaN,NaN,75166,NaN,NaN,13877,NaN,...,NaN,NaN,NaN,79330,56477,97870,89613,104641,92310,75166
mean,59695.500000,1.664461,4.262032,5.089044,1.380526,NaN,104.011416,2016.156554,NaN,27.165173,...,0.571363,2016-07-30 00:24:47.883407104,2016-08-28 16:39:45.727447808,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.000000,2015.000000,NaN,1.000000,...,0.000000,2014-10-17 00:00:00,2015-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,29848.250000,1.000000,3.000000,1.000000,1.000000,NaN,18.000000,2016.000000,NaN,16.000000,...,0.000000,2016-02-01 00:00:00,2016-03-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,59695.500000,2.000000,3.000000,3.000000,1.000000,NaN,69.000000,2016.000000,NaN,28.000000,...,0.000000,2016-08-07 00:00:00,2016-09-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,89542.750000,2.000000,4.000000,8.000000,2.000000,NaN,160.000000,2017.000000,NaN,38.000000,...,1.000000,2017-02-08 00:00:00,2017-03-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,119390.000000,2.000000,26.000000,36.000000,3.000000,NaN,737.000000,2017.000000,NaN,53.000000,...,5.000000,2017-09-14 00:00:00,2017-08-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,34465.068657,0.472181,3.071532,5.250009,0.505913,NaN,106.863097,0.707476,NaN,13.605138,...,0.792798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
# remove duplicate fields
df = df.drop(columns=['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month','Hotel_ID', 'Market_Segment_ID', 'Customer_Type_ID', 'Reservation_ID'
])

#### Export data to new CSV file

In [77]:
# export df into CSV file
# f.to_csv('bookings_final.csv', index=False)

# from google.colab import files
# files.download('bookings_final.csv')

In [62]:
# Final step of data cleansing: no nulls remain, so use standard integer types
int_cols = ['children', 'agent', 'company']
assert df[int_cols].isna().sum().sum() == 0
df[int_cols] = df[int_cols].astype('int64')

### 4. Visualization for Research Objective

In [63]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np, pandas as pd
import matplotlib.pyplot as plt, matplotlib.ticker as mtick
from matplotlib.colors import LinearSegmentedColormap
from scipy.stats import chi2_contingency

# ---- Chart style: one validated palette, recessive grid, no dual axes ----
BLUE, ORANGE, AQUA = '#2a78d6', '#eb6834', '#1baf7a'          # categorical slots 1–3
INK, INK2, MUTED   = '#0b0b0b', '#52514e', '#8a8984'
CONTEXT = '#c9c7c0'                                            # neutral bars for volume / context
GRID, SURFACE = '#e6e5e1', '#fcfcfb'
HOTEL_COLORS = {'City Hotel': BLUE, 'Resort Hotel': ORANGE}
SEQ = LinearSegmentedColormap.from_list('seq_blue',
        ['#cde2fb', '#9ec5f4', '#6da7ec', '#3987e5', '#256abf', '#184f95', '#0d366b'])

plt.rcParams.update({
    'figure.facecolor': SURFACE, 'axes.facecolor': SURFACE, 'savefig.facecolor': SURFACE,
    'axes.edgecolor': GRID, 'axes.labelcolor': INK2, 'xtick.color': INK2, 'ytick.color': INK2,
    'text.color': INK, 'axes.titlecolor': INK, 'axes.titlesize': 11, 'axes.titleweight': 'bold',
    'axes.titlelocation': 'left', 'axes.spines.top': False, 'axes.spines.right': False,
    'axes.grid': True, 'grid.color': GRID, 'grid.linewidth': 0.8, 'axes.axisbelow': True,
    'font.size': 10, 'legend.frameon': False, 'figure.dpi': 110, 'lines.linewidth': 2,
    'xtick.major.size': 0, 'ytick.major.size': 0})
PCT = mtick.PercentFormatter(1.0, decimals=0)
THOU = mtick.FuncFormatter(lambda v, _: f'{v:,.0f}')

def suptitle(fig, text, sub=None, gap=1.0):
    # Title + subtitle anchored in inches from the top, so they never collide with the plot
    H = fig.get_figheight()
    fig.text(0.01, 1 - 0.10 / H, text, ha='left', va='top', fontsize=13, fontweight='bold')
    if sub: fig.text(0.01, 1 - 0.38 / H, sub, ha='left', va='top', fontsize=9.5, color=INK2)
    fig.subplots_adjust(top=1 - gap / H)

In [64]:
# Source: the cleaned DataFrame `df` from the data-cleansing section of this notebook.
# Work on a copy so the analysis columns added below don't alter the cleansed data.
df = df.copy()

# Align types: nullable Int64 -> int64 (no nulls remain after cleansing), dates -> datetime
for c in df.select_dtypes(include='Int64').columns:
    df[c] = df[c].astype('int64')
for c in ['checkin_date', 'reservation_status_date']:
    df[c] = pd.to_datetime(df[c])
df['is_canceled'] = df['is_canceled'].astype(int)
df['is_repeated_guest'] = df['is_repeated_guest'].astype(int)

# ---- Derived fields used across objectives ----
# All arrival-period fields come from checkin_date (the final arrival date); the raw arrival_date_* columns are not used
df['arrival_month'] = df['checkin_date'].dt.to_period('M')
df['arrival_week'] = df['checkin_date'].dt.isocalendar().week.astype(int)
MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
df['arrival_mname'] = pd.Categorical(df['checkin_date'].dt.strftime('%b'), MONTHS, ordered=True)
df['total_nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
df['kids'] = df['children'] + df['babies']

def band(s, edges, labels):
    return pd.cut(s, edges, labels=labels, right=True, include_lowest=True)

LEAD = ['0–7', '8–30', '31–90', '91–180', '181–365', '366+']
df['lead_band'] = band(df['lead_time'], [-1, 7, 30, 90, 180, 365, np.inf], LEAD)
STAY = ['0', '1', '2–3', '4–7', '8–14', '15+']
df['stay_band'] = band(df['total_nights'], [-1, 0, 1, 3, 7, 14, np.inf], STAY)
CHG = ['0', '1', '2', '3+']
df['changes_band'] = band(df['booking_changes'], [-1, 0, 1, 2, np.inf], CHG)
REQ = ['0', '1', '2', '3+']
df['requests_band'] = band(df['total_of_special_requests'], [-1, 0, 1, 2, np.inf], REQ)
WAIT = ['0', '1–7', '8–30', '31–90', '91+']
df['wait_band'] = band(df['days_in_waiting_list'], [-1, 0, 7, 30, 90, np.inf], WAIT)
df['waited'] = (df['days_in_waiting_list'] > 0).astype(int)

PARTY = ['Solo adult', 'Couple (2 adults)', '3+ adults', 'With children', 'No adults / unknown']
df['party'] = np.select(
    [df['adults'].eq(0), df['kids'].gt(0), df['adults'].eq(1), df['adults'].eq(2)],
    ['No adults / unknown', 'With children', 'Solo adult', 'Couple (2 adults)'], '3+ adults')
df['party'] = pd.Categorical(df['party'], PARTY, ordered=True)

df['prev_cancel_flag'] = (df['previous_cancellations'] > 0).astype(int)
df['prev_stay_flag'] = (df['previous_bookings_not_canceled'] > 0).astype(int)
df['has_agent'] = (df['agent'] > 0).astype(int)
df['has_company'] = (df['company'] > 0).astype(int)

# 7 bookings carry an 'Undefined' segment/channel — excluded from segment-level views
seg = df[(df['market_segment'] != 'Undefined') & (df['distribution_channel'] != 'Undefined')].copy()

BASE = df['is_canceled'].mean()
print(f"Bookings: {len(df):,}   Cancelled + no-show: {df['is_canceled'].sum():,}   Baseline rate: {BASE:.2%}")
print(df['reservation_status'].value_counts().to_string())

Bookings: 119,390   Cancelled + no-show: 44,224   Baseline rate: 37.04%
reservation_status
Check-Out    75166
Canceled     43017
No-Show       1207

In [65]:
def rate_table(data, col, order=None):
    t = data.groupby(col, observed=True)['is_canceled'].agg(bookings='size', cancellations='sum')
    t['cancel_rate'] = t['cancellations'] / t['bookings']
    if order is not None:
        t = t.reindex([o for o in order if o in t.index])
    return t

def baseline_v(ax, label=True, y=None):
    ax.axvline(BASE, color=INK2, lw=1, ls=(0, (4, 3)), zorder=3)
    if label:
        ax.text(BASE, ax.get_ylim()[1] if y is None else y, f' overall {BASE:.1%}',
                color=INK2, fontsize=8.5, va='bottom', ha='left')

def baseline_h(ax, label=True):
    ax.axhline(BASE, color=INK2, lw=1, ls=(0, (4, 3)), zorder=3)
    if label:
        ax.text(ax.get_xlim()[1], BASE, f'overall {BASE:.1%} ', color=INK2, fontsize=8.5,
                va='bottom', ha='right')

def volume_rate_panel(data, col, title, sub=None, order=None):
    # Two aligned panels (one measure each, no dual axis): volume as context, rate as the story
    t = rate_table(data, col, order)
    if order is None:
        t = t.sort_values('cancel_rate')
    y = np.arange(len(t))
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(11, 0.5 * len(t) + 1.9), sharey=True,
                                 gridspec_kw={'width_ratios': [1, 1.25], 'wspace': 0.12})
    a1.barh(y, t['bookings'], color=CONTEXT, height=0.62)
    a1.set_yticks(y, t.index); a1.set_title('Bookings'); a1.xaxis.set_major_formatter(THOU); a1.xaxis.set_major_locator(mtick.MaxNLocator(4))
    a1.set_xlim(0, t['bookings'].max() * 1.28); a1.grid(axis='y', visible=False)
    for yi, v in zip(y, t['bookings']):
        a1.text(v, yi, f' {v:,}', va='center', fontsize=8.5, color=INK2)
    a2.barh(y, t['cancel_rate'], color=BLUE, height=0.62)
    a2.set_title('Cancellation rate'); a2.xaxis.set_major_formatter(PCT)
    a2.set_xlim(0, max(t['cancel_rate'].max(), BASE) * 1.2); a2.grid(axis='y', visible=False)
    for yi, v in zip(y, t['cancel_rate']):
        a2.text(v, yi, f' {v:.1%}', va='center', fontsize=8.5, color=INK)
    a2.set_ylim(-0.6, len(t) - 0.4)
    baseline_v(a2, y=len(t) - 0.45)
    suptitle(fig, title, sub)
    plt.show()
    return t

## RO1 — Volumes and cancellation rates by hotel, arrival period, market segment and channel

## RO2 — Booking characteristics associated with cancellation

## RO3 — Waiting-list days and cancellation

## RO4 — Repeat guests and previous booking history by market segment

## RO5 — High-volume, high-risk booking profiles